{
 "title": "drydock",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "docker_host",
    "label": "Docker Host",
    "query": {
     "query": "label_values(dd_containers,watcher)"
    }
   },
   {
    "name": "container_image",
    "label": "Image",
    "query": {
     "query": "label_values(dd_containers,image_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Images Monitored",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dd_containers{watcher=~\"${docker_host:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Major Updates Available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dd_containers{update_available=\"true\", update_kind_semver_diff=\"major\", watcher=~\"${docker_host:pipe}\", image_name=~\"${container_image:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minor Updates Available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dd_containers{update_available=\"true\", update_kind_semver_diff=\"minor\", watcher=~\"${docker_host:pipe}\", image_name=~\"${container_image:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Patch Updates Available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dd_containers{update_available=\"true\", update_kind_semver_diff=\"patch\", watcher=~\"${docker_host:pipe}\", image_name=~\"${container_image:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitored Containers",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "group by(display_name, update_kind_remote_value, update_kind_semver_diff, watcher, image_tag_value, link) (dd_containers{watcher=~\"${docker_host:pipe}\", image_name=~\"${container_image:pipe}\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}